name: PyTest 
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
       # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base

      - name: Add $PYTHONPATH
        run: |
          echo "PYTHONPATH=/home/runner/work/scheduler/scheduler" >> $GITHUB_ENV
      
      - name: Generate Report
        run: |
          $CONDA/bin/coverage run -m pytest
          $CONDA/bin/coverage xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
          